title: My Jekyll Site
description: A simple blog powered by Jekyll
baseurl: ""
url: "https://esonparedes.github.io"
author:
  name: Jason Paredes
  email: esonparedes@hotmail.com
theme: minima
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - _posts
  - _drafts
  - _includes
  - _layouts
  - _sass
  - assets
  - index.html
  - _config.yml
